version: 2

formats:
  - epub
  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py  

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - setup.py
    - requirements: docs/requirements.txt

